// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_NS-qTdM-RHkPKntzd7deW4V54mIqCc',
    appId: '1:589498492064:web:e2a54cdf0587adaf6e95c5',
    messagingSenderId: '589498492064',
    projectId: 'firetest-mo',
    authDomain: 'firetest-mo.firebaseapp.com',
    storageBucket: 'firetest-mo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA54fbOdvPevVOyPRjhhyTXdYa0Do-bcU4',
    appId: '1:589498492064:android:fb359ff70de72b266e95c5',
    messagingSenderId: '589498492064',
    projectId: 'firetest-mo',
    storageBucket: 'firetest-mo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW6BqRcXtgWMEnXprlTubS1gKuNWO12ok',
    appId: '1:589498492064:ios:3d9824a2dbd7ddea6e95c5',
    messagingSenderId: '589498492064',
    projectId: 'firetest-mo',
    storageBucket: 'firetest-mo.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW6BqRcXtgWMEnXprlTubS1gKuNWO12ok',
    appId: '1:589498492064:ios:3d9824a2dbd7ddea6e95c5',
    messagingSenderId: '589498492064',
    projectId: 'firetest-mo',
    storageBucket: 'firetest-mo.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF_NS-qTdM-RHkPKntzd7deW4V54mIqCc',
    appId: '1:589498492064:web:fb03edc080f020666e95c5',
    messagingSenderId: '589498492064',
    projectId: 'firetest-mo',
    authDomain: 'firetest-mo.firebaseapp.com',
    storageBucket: 'firetest-mo.firebasestorage.app',
  );

}